### ISSUE TITLE
configure script not checked into git, please attach

### ISSUE THREAD

**Issue by eddo888** [retostockli/xpcockpit#23]
Hi, the ./configure script is not in the git repository, can you please check it in.

**Comment by eddo888** [comment]
ok, so automake creates said configure file, I remove my issue.

**Comment by retostockli** [comment]
Yes. The configure script is auto-generated which best reflects your system configuration.
Do you use the master branch? It has not been updated for a while. We have many many additions in the B737 branch, including auto-detection of X-Plane etc. 
I will update the master branch in 1-2 weeks with those changes. But I motivate you to try the B737 branch if you want.

**Comment by retostockli** [comment]
Also note that the whole system has not yet been tested with X-Plane 12.
